# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 458d87b49ec86b50df8d8bf6ee7a0fa4e04abfdf76293c253ff42add137e1cc43be19f5c3ea93e57b4699ace3a748ecfd6ab2860445c8bcd1ffa9c451c419944

test:
  secret_key_base: 1d303172fa07750dad8079d0f1c4a59b62de8902b8ec130409beb74a604e9b39f10736212b294cd112a3858878a947450ad9c407d0266f60377105e0c1010eee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
